# Generated by Django 4.1.2 on 2022-10-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="slackUsernae",
            new_name="slackUsername",
        ),
    ]
